env:
  browser: true
  node: true
  es2021: true

extends:
  - standard-with-typescript
  - next/core-web-vitals
  - prettier

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 'latest'
  sourceType: 'module'
  project: './tsconfig.eslint.json'
  jsx: true

rules:
  import/order:
    - 'warn'
    - groups:
        - 'builtin'
        - 'external'
        - 'internal'
        - 'parent'
        - 'sibling'
        - 'index'
        - 'object'
        - 'type'
      newlines-between: 'always'
      pathGroupsExcludedImportTypes: ['builtin']
      alphabetize:
        order: 'asc'
        caseInsensitive: true
  eqeqeq: 'error'
  '@typescript-eslint/no-misused-promises':
    - 'error'
    - checksVoidReturn:
        attributes: false
  '@typescript-eslint/consistent-type-definitions':
    - 'error'
    - 'type'
  react/jsx-sort-props: 'warn'

overrides:
  - files: ['next-env.d.ts']
    rules:
      '@typescript-eslint/triple-slash-reference': 'off'
