ls:
  .js: camelCase | regex:^\.[a-z]+(?:[A-Z][a-z]+)*$
  .config.js: camelCase
  .ts: camelCase | regex:^\$[a-z]+(?:[A-Z][a-z]+)*$
  .d.ts: camelCase
  .css.ts: camelCase
  .tsx: camelCase | regex:^\_[a-z]+(?:[A-Z][a-z]+)*$
  .stories.tsx: camelCase

  .json: kebab-case | regex:^\.[a-z]+(?:-[a-z]+)*$
  .yml: kebab-case | regex:^\.[a-z]+(?:-[a-z]+)*$

  .svg: camelCase
  .jpg: kebab-case
  .jpeg: kebab-case
  .png: kebab-case
  .webp: kebab-case
  .avif: kebab-case

  .md: kebab-case

ignore:
  - node_modules
  - .next
  - out
  - next-env.d.ts
  - README.md
  - storybook-static
  - tsconfig.eslint.json
