// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Hoge struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type NewHoge struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
