name: Deploy Chromatic

on:
  push:
    branches-ignore:
      - dependabot/**
      - gh-pages

jobs:
  deploy-chromatic:
    runs-on:
      - ubuntu-latest

    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0

      - name: Upgrade to yarn
        run: yarn set version 4.0.2

      - name: Get yarn cache directory path
        id: cache_dir_path
        run: echo "CACHE_DIR_PATH=$(yarn config get cacheFolder)" >> $GITHUB_ENV

      - name: Cache yarn cache directory
        uses: actions/cache@v3
        with:
          path: ${{ env.CACHE_DIR_PATH }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable --check-cache

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
