name: Publish Lighthouse

on:
  push:
    branches-ignore:
      - gh-pages

jobs:
  publish-lighthouse:
    runs-on:
      - ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy env file
        run: cp .env.example .env

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0

      - name: Install dependencies
        run: yarn install

      - name: Build Next.js app
        run: yarn build

      - name: Start production server
        run: yarn start &

      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: http://localhost:3000/
          uploadArtifacts: true
          temporaryPublicStorage: false

      - name: Generate directory name
        id: dir_name
        run: |
          DIR_NAME=${{ github.ref }}
          DIR_NAME=${DIR_NAME#refs/heads/}
          DIR_NAME=${DIR_NAME////_}
          echo "DIR_NAME=$DIR_NAME" >> $GITHUB_ENV

      - name: Move Lighthouse report
        run: |
          mkdir -p dist/$DIR_NAME/lighthouse
          mv .lighthouseci/lhr-*.html dist/$DIR_NAME/lighthouse/index.html

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          keep_files: true
          user_name: uyupunpopunpo
          user_email: uyupun@gmail.com
