name: Publish Storybook

on:
  push:

jobs:
  publish-storybook:
    runs-on:
      - ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0

      - name: Install dependencies
        run: yarn install

      - name: Build Storybook
        run: yarn run build-storybook
